### ISSUE TITLE
Add support for clouds-public.yaml and secure.yaml

### ISSUE THREAD

**Issue by mchlumsky** [dtantsur/rust-osauth#15]
Add support for clouds-public.yaml and secure.yaml as defined [here](https://docs.openstack.org/openstacksdk/latest/user/config/configuration.html#config-files).

**Comment by mchlumsky** [comment]
If you don't mind, I can work on this one.

**Comment by dtantsur** [comment]
@mchlumsky hi, I don't mind it at all, thank you! :)

**Comment by mchlumsky** [comment]
Pull request: https://github.com/dtantsur/rust-osauth/pull/16

**Comment by dtantsur** [comment]
Closed in #16
