### ISSUE TITLE
Can't authenticate when project_domain_name is omitted in clouds.yaml

### ISSUE THREAD

**Issue by jistr** [dtantsur/rust-osauth#9]
From the clouds.yaml entries below, the one named `works` works both when using rust-osauth and the normal Python-based `openstack` CLI. The entry named `doesnotwork` (where `project_domain_name` is not specified) only works with the openstack CLI but not with rust-osauth.

The workaround is to add `project_domain_name` entry with the same value as `user_domain_name`.

(This is a bit out of my comfort zone, i'm not sure which one of the clients exhibits unexpected behavior here. But maybe it's worth following the openstackclient behavior either way. I'm not sure if i'll find time to dive deeper soon, but wanted to at least report this.)

    clouds:

      works:
        auth:
          auth_url: https://redacted/v3
          username: "redacted"
          project_id: redacted
          project_name: "redacted"
          project_domain_name: "redacted"
          user_domain_name: "redacted"
          password: "redacted"
        region_name: "regionOne"
        interface: "public"
        identity_api_version: 3

      doesnotwork:
        auth:
          auth_url: https://redacted/v3
          username: "redacted"
          project_id: redacted
          project_name: "redacted"
          user_domain_name: "redacted"
          password: "redacted"
        region_name: "regionOne"
        interface: "public"
        identity_api_version: 3

**Comment by dtantsur** [comment]
Hi Jirka! :) Hmm, I'm not sure why OSC works without project domain. I honestly thought a domain is required for a project-scoped auth. I'll take a look.

**Comment by dtantsur** [comment]
Okay, it seems that OSC just uses the default of `default`. I'm not sure I like it, especially since openstacksdk does not have a default:
```
keystoneauth1.exceptions.http.BadRequest: Expecting to find domain in project. The server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-e07e16e1-6ac6-4ba4-830d-e610e6b9884d)
```

**Comment by jistr** [comment]
Ok that makes sense, perhaps this is a notabug and we can close this issue then. (Grey area -- i can see how defaulting might help for user convenience, OTOH for programming API i can see that we may want to be strict.)

Now that i read the above BadRequest exception, i recall that i haven't seen "Expecting to find domain in project." in the log output of rust-osauth (i just trial-errored the workaround). And IIUC i was getting 401 and not 400, so there may still be some difference between how rust-osauth and openstacksdk handles this -- the error from openstacksdk looks more granular/helpful. That's a very vague way to report an issue though :), i may circle back to retest if i get some more time for this, and perhaps create a separate issue.

**Comment by jistr** [comment]
Thanks for the reply :)

**Comment by dtantsur** [comment]
I've just checked locally, and it seems that missing domains quite happily default to `Default`. Not sure when it was changed, but it seems to work now.
